site_name: Anisha
nav:
    - Home: index.md
    - About: about.md
    - My Stories: stories.md
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    primary: light green  