site_name: Anisha
nav:
    - Home: index.md
    - About: about.md
    - Blogs: blogs.md
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    primary: blue  
